//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Card_ID { get; set; }
        public int Catalog_ID { get; set; }
        public int Position { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
