//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Card
    {
        [Key]
        public int Card_ID { get; set; }
        public string Title { get; set; }

        public string Description { get; set; }

        public int Position { get; set; }

        // Внешний ключ для связи с Catalog
        public int Catalog_ID { get; set; }

        // Навигационное свойство, которое указывает на Catalog
        public virtual Catalog Catalog { get; set; }
    }

}
